networks:
  kind:
    external: true
    name: kind

services:
  postgres:
    image: postgres:17
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - kind

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP interface
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: app_user
      CLICKHOUSE_PASSWORD: app_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    networks:
      - kind
