apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airbyte-v2
  namespace: airbyte-v2
spec:
  interval: 30m0s
  chart:
    spec:
      chart: airbyte
      version: v2.0.19
      sourceRef:
        kind: HelmRepository
        name: airbyte-v2
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: Create
  values:
    serviceAccountName: &service-account-name airbyte-admin
    edition: community
    secretName: ""
    local: false
    global:
      airbyteUrl: "http://airbyte.localtest.me"
    cluster:
      type: hybrid
      secretName: ""
      controlPlane:
        bootstrap:
          dataPlane:
            secretName: ""
            clientIdSecretKey: ""
            clientSecretSecretKey: ""
      dataPlane:
        controlPlaneAuthEndpoint: ""
    enterprise:
      secretName: ""
      licenseKeySecretKey: ""
    ingress:
      enabled: false
      className: nginx
      annotations: {}
      hosts:
        - host: airbyte.localtest.me
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
    webapp:
      enabled: true
      image:
        repository: airbyte/webapp
        pullPolicy: IfNotPresent
        tag: 2.0.1
      ingress:
        enabled: true
